### ISSUE TITLE
Features for blog widget (free version)

### ISSUE THREAD

**Issue by nickburne** [PootlePress/blog-widget#1]
1. Show featured image checkbox
2. Show post titles checkbox
3. Show all meta checkbox
4. Show excerpt checkbox

Possible options for pro:
1. post type option (post, page, custom post type etc)
2. Add new options - a list of categories to choose from (in checkboxes)
3. Featured image positioning
4. Featured image sizes
5. Set excerpt size
6. Pagination
7. Show dates checkbox
8. Show categories checkbox
9. Show continue reading checkbox
10. Show comments checkbox
11. Show author checkbox
12. Date configuration

**Comment by shrameesrivastav** [comment]
Hi,
Nick,
Just got the free version ready, let me know if any amendments are required.

Cheers

**Comment by nickburne** [comment]
Thanks Vijay! I will take a look!

**Comment by nickburne** [comment]
Looks great Vijay. I will add some separate tickets and close this one...
