### ISSUE TITLE
Title and featured image should be links to the post page

### ISSUE THREAD

**Issue by nickburne** [PootlePress/blog-widget#2]
Do you agree? If so, please go ahead. If not, let me know what you think!

**Comment by shrameesrivastav** [comment]
Hmmmm... I do
Lets get this done.

**Comment by shrameesrivastav** [comment]
Done, Kindly check this out.

**Comment by shrameesrivastav** [comment]
How about adding an option to choose to do it?

**Comment by shrameesrivastav** [comment]
For free version we can have only one option making it happen for both the title and the image and in paid version we can have em seperate ie two option one for title and one for image??

Whaddya say?

**Comment by nickburne** [comment]
I like this suggestion. I think we should make the title and image link by default in the free version and put the option to turn this off for both in the paid version. I will add this to the paid version.

Good suggestion!

This is now closed.
