### ISSUE TITLE
Problem with blog widget on page builder page AND sidebar

### ISSUE THREAD

**Issue by nickburne** [PootlePress/blog-widget#3]
![screenshot 2015-02-09 16 00 12](https://cloud.githubusercontent.com/assets/3784875/6109717/c62b2588-b074-11e4-8b4e-7c74d6bd169c.png)

We probably need to make these able to work together somehow.

**Comment by shrameesrivastav** [comment]
Done, Kindly check this one too!!

**Comment by nickburne** [comment]
Good fix!
