### ISSUE TITLE
Featured images in the sidebar stretch vertically

### ISSUE THREAD

**Issue by nickburne** [PootlePress/blog-widget#5]
They should really be proportional... do you agree? If so, please fix.

**Comment by nickburne** [comment]
Actually - it's not just sidebar. Seems like featured images adjust width fine, just not height, whereever they are placed... Please fix..

**Comment by shrameesrivastav** [comment]
Will check this out.

**Comment by shrameesrivastav** [comment]
And what happened to Skype??
Couldn't hear from you the whole day!!

**Comment by shrameesrivastav** [comment]
Sorry if it seems like I'm yelling at you thanks to the two exclamations... obviously I didn't mean to.

**Comment by shrameesrivastav** [comment]
Got it done.

**Comment by nickburne** [comment]
Good fix!
