### ISSUE TITLE
Pro verses free version

### ISSUE THREAD

**Issue by nickburne** [PootlePress/blog-widget#6]
Quick question.

Is it easier to develop the PRO version with all the options and then take the free version from this one and limit the options. 

This would save developing 2 different plugins. We could build this into 1 plugin and then just change one setting before creating the free plugin...

Get me?

What do you think??

N

**Comment by shramee** [comment]
Yeah we can do it, using this plugin as boilerplate ; )

**Comment by shramee** [comment]
And yeah forgot to mention that we had done some work on BW pro before left Magnon and before I got to know about SFX-PC stuff.

**Comment by nickburne** [comment]
Yes - this is the same repository you were working on before.

Ok - we will make the PRO version here and then create the free one out of it later...
